--- #YAML:1.0
name:               In-Korean-Numbers-SinoKorean
version:            0.03
abstract:           Convert integers to Sino-Korean text (in Hangul) and vice versa.
author:
    - Bryan Smith <bryan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
